### PR TITLE
remove comments from rst

### PR DESCRIPTION
**Pull request by jspaaks**
**List of related issues or pull requests**

Refs: #272

**Describe the changes made in this pull request**

- Updated the workaround for removing comments from ReStructuredText.
- Added tests with various comments
- moved removing comments from rst to be part of normal `Readme`, no longer under `workarounds`
- excluded contents of `snippets` directory from `.editorconfig`'s scrutiny and automatic updates
- (Unrelated) Also removed pylint githook, prospector already runs it in the first step

**Instructions to review the pull request**

```
# in an activated venv with dev dependencies installed
pytest tests/remove_comments_rst
pytest tests/
pytest livetests/
bash clitests/script.sh
```

### CODE REVIEW

**Review by sverhoeven — CHANGES_REQUESTED** [review]
Great that you found a way to drop comments.

Can a test be added with actual commented out badge snippet?

```rst
.. .. |pypi badge| image:: https://img.shields.io/pypi/v/howfairis.svg?colorB=blue
..    :target: https://pypi.python.org/pypi/howfairis/
```

More things In PR description than visible
- `remove_comments_rst()` should be part of `Readme`, but currently it is still part of `workarounds/`. Can you clarify?
- expected changes to .editorconfig, but non seen. Can you clarify?
- pylint githook is still there. Can you clarify?

**Comment by jspaaks** [comment]
Added a test for commented images and commented urls to `tests/remove_comments_rst/snippets/4-original.rst`

**Review by sverhoeven — APPROVED** [review]
Thanks for adding the test.

Can `testremove_comments_rst/*expected.rst` except `tests/remove_comments_rst/snippets/5-expected.rst` be removed as they are not used in test code?

**Comment by jspaaks** [comment]
> Thanks for adding the test.
> 
> Can `testremove_comments_rst/*expected.rst` except `tests/remove_comments_rst/snippets/5-expected.rst` be removed as they are not used in test code?

Did that in https://github.com/fair-software/howfairis/pull/314, merging this

**Pull request merged**
