### PR TITLE
Exit during installation of incompatible Python versions

### PR DESCRIPTION
**Pull request by sverhoeven**
Code copied from https://github.com/ipython/ipython/blob/6a3e2db0c299dc05e636653c4a43d0aa756fb1c8/setup.py#L23-L58

Refs #73

Tested with
```shell
sudo python3.5 setup.py install

howfairis supports Python 3.6 and above.

See howfairis `README.rst` file for more information:

https://github.com/fair-software/howfairis/blob/master/README.rst

Python 3.5.2 detected.

echo $?
1
```

### CODE REVIEW

**Comment by fdiblen** [comment]
It would be easier to use `python-requires` to define supported Python versions.

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by sverhoeven** [comment]
> It would be easier to use `python-requires` to define supported Python versions.
> 
> https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

`python-requires` depends on a recent pip installation, people using an old Python probably also have a old pip so that will not be that portable.

**Comment by sverhoeven** [comment]
Now refs #212

**Comment by sverhoeven** [comment]
We have not had anyone with this problem, lets fix it when it occurs. Please reopen if needed.

**Pull request closed without merging**
